### Python for Data Analysis and Machine Learning

#### Numpy

In [3]:
import numpy as np
nums=[1,2.0,-1.3]
arr=np.array(nums)
print(f'A numpy array: {arr}')

A numpy array: [ 1.   2.  -1.3]


In [6]:
nums2=[-2.3,-4,6]
arr2=np.array([nums,nums2])
print(f'A list of lists: \n{nums,nums2}')

A list of lists: 
([1, 2.0, -1.3], [-2.3, -4, 6])


In [7]:
print(f'A numpy 2D array: \n{arr2}')

A numpy 2D array: 
[[ 1.   2.  -1.3]
 [-2.3 -4.   6. ]]


#### ndarray math

In [11]:
a=np.array([1,2,3,4])
b=np.array([4,5,6,7])
print(a-b)

[-3 -3 -3 -3]


In [12]:
c=a/b
print(type(c))

<class 'numpy.ndarray'>


In [14]:
c=a*b
print(c)

[ 4 10 18 28]


In [15]:
c=a+b
print(c)

[ 5  7  9 11]


In [16]:
c=a-b
print(c)

[-3 -3 -3 -3]


In [17]:
c=a/b
print(c)

[0.25       0.4        0.5        0.57142857]


In [18]:
#Broadcasting
-2*a

array([-2, -4, -6, -8])

In [19]:
#Combinations...
-2*a+b**2

array([14, 21, 30, 41])

In [49]:
a=np.array([10,20,30,40])
b=np.array([[1,2,3,4],
          [4,5,6,7,],
          [1,1,1,1],
          [2,2,2,2]])
a+b

array([[11, 22, 33, 44],
       [14, 25, 36, 47],
       [11, 21, 31, 41],
       [12, 22, 32, 42]])

#### ndarray sizes and reshaping

In [22]:
a.size

4

In [23]:
b.size

16

In [27]:
a.shape

(4,)

In [28]:
b.shape

(4, 4)

In [34]:
d=np.array([1,2,3,4,5,6,7,8,9])
d.shape

(9,)

In [35]:
d_2d=d.reshape((3,3))
d_2d.shape

(3, 3)

In [38]:
d_col=d.reshape((1,9))
d_col.shape

(1, 9)

In [42]:
#Transpose it
d_row=d_col.T
d_row.shape

(9, 1)

In [40]:
d_3d=d.reshape((1,3,3))
d_3d.size

9

In [41]:
d_3d.shape

(1, 3, 3)

In [43]:
d_col

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [44]:
d_row

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [45]:
d_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [46]:
d_3d

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [52]:
# A vector is always treated as a row. If you want to do operations by columns,make the vector a 2D array where one dimension is of size 1
a=np.array([10,20,30,40]).reshape((4,1))
b=np.array([[1,2,3,4],
          [4,5,6,7,],
          [1,1,1,1],
          [2,2,2,2]])
a+b

array([[11, 12, 13, 14],
       [24, 25, 26, 27],
       [31, 31, 31, 31],
       [42, 42, 42, 42]])

In [53]:
a.T+b

array([[11, 22, 33, 44],
       [14, 25, 36, 47],
       [11, 21, 31, 41],
       [12, 22, 32, 42]])

#### Multiplication

In [54]:
a=np.array([[1,0],[0,1]])
b=np.array([[4,1],[2,2]])
np.dot(a,b)

array([[4, 1],
       [2, 2]])

In [55]:
a@b

array([[4, 1],
       [2, 2]])

In [56]:
np.cross(a,b)

array([ 1, -2])

In [57]:
a.dtype

dtype('int32')

In [58]:
b.dtype

dtype('int32')

In [63]:
b=b.astype('float64')
b.dtype

dtype('float64')

#### ndarray from numpy initialization

In [1]:
import numpy as np
arrex1=np.zeros(5)
print(arrex1)

[0. 0. 0. 0. 0.]


In [2]:
arrex2=np.zeros([5,])
print(arrex2)

[0. 0. 0. 0. 0.]


In [3]:
arrex2=np.zeros([5,5])
print(arrex2)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [5]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [7]:
np.ones((5,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [8]:
np.full((2,2),np.inf)

array([[inf, inf],
       [inf, inf]])

In [13]:
np.full((2,2),[1,2])

array([[1, 2],
       [1, 2]])

#### ndarray indexing

In [14]:
oneD=np.array([1,2,3,4])
twoD=oneD.reshape([2,2])

In [15]:
twoD

array([[1, 2],
       [3, 4]])

In [16]:
oneD[0]

1

In [17]:
oneD[3]

4

In [18]:
oneD[-1]

4

In [19]:
oneD[-2]

3

In [20]:
twoD[0,0]

1

In [21]:
twoD[1,0]

3

#### ndarray slicing

In [23]:
y=np.arange(50,300,50)

In [30]:
print(y[0:3])

[ 50 100 150]


In [41]:
print(y[-1:-3:-1])

[250 200]


In [32]:
x=np.arange(10,130,10).reshape(4,3)

In [43]:
print(x[:,0])

[ 10  40  70 100]


In [34]:
print(x[2:4,1:3])

[[ 80  90]
 [110 120]]


In [52]:
y[0:3]=-1
y[0:8]=-1

In [53]:
print(y)

[-1 -1 -1 -1 -1]


In [55]:
x=np.array([10,20,30,40,50,60])
y[0:2]=x[3:5]
print(y)

[40 50 -1 -1 -1]


In [58]:
a=np.linspace(-1,1,5)
print(a)

[-1.  -0.5  0.   0.5  1. ]


In [59]:
b=np.array([0,1,2])

In [60]:
print(a[b])

[-1.  -0.5  0. ]


In [61]:
c=np.array([True,False,True,True,False])
print(a[c])

[-1.   0.   0.5]


In [62]:
np.where(a<=0)

(array([0, 1, 2], dtype=int64),)

In [63]:
np.where(a<=0,-a,20*a)

array([ 1. ,  0.5, -0. , 10. , 20. ])